#!/usr/bin/env php
<?php
declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';
require "app/bootstrap.php";

use App\Commands\GetWeatherCommand,
    GuzzleHttp\Client;

$client = new Client();
$app = new GetWeatherCommand($client, $apiCredentials);

array_shift($argv);
$app->getWeather($argv);
